### ISSUE TITLE
Gutter is the same color as the text area

### ISSUE THREAD

**Issue by matklad** [matklad/pale-fire#13]
Emacs:

![image](https://user-images.githubusercontent.com/1711539/87858324-5f6e5900-c92d-11ea-91cf-da7da2002bb6.png)

VS Code:

![image](https://user-images.githubusercontent.com/1711539/87858333-6dbc7500-c92d-11ea-9ec9-86341ccd2f2b.png)

**Comment by matklad** [comment]
Although I am actually not sure if this is bad... VS Code's gutter area is **huge**, so high contrast doesn't look as pretty

**Comment by arzg** [comment]
Sorry, what do you mean with ‘high contrast’?

**Comment by arzg** [comment]
Ah, I see. I noticed when I looked at your VS Code config to implement #4 that you used various settings (some documented, some undocumented) to make the gutter as small as possible. I think it would be quite strange to make a change to the UI that only looks good if you use undocumented settings.

Based on the colours in the screenshot and [your personal config](https://github.com/matklad/config/blob/9b0d2d187bb1ac57b489bb34df8af48b6f8899e8/home/.config/Code/User/settings.json#L136) I’m guessing that you’re proposing `#4F4F4F` for the colour of the gutter.

Here’s a screenshot of VS Code with the following `settings.json`:

```json
{
    "workbench.colorTheme": "Pale Fire"
}
```

<img width="1339" alt="Screen Shot 2020-07-19 at 10 20 08 pm" src="https://user-images.githubusercontent.com/31783266/87874539-01fe0900-ca0e-11ea-878a-1e47255704d5.png">

With your suggested gutter colour:

```json
{
    "workbench.colorTheme": "Pale Fire",
    "workbench.colorCustomizations": {
        "editorGutter.background": "#4F4F4F"
    }
}
```

<img width="1339" alt="Screen Shot 2020-07-19 at 10 18 55 pm" src="https://user-images.githubusercontent.com/31783266/87874525-d67b1e80-ca0d-11ea-8203-31495dfc825c.png">

I personally agree with you in that the gutter looks too prominent – what if we used the colour in between `#4F4F4F` (zenburn-bg+1) and the background: zenburn-bg+05 (`#494949`)?

```json
{
    "workbench.colorTheme": "Pale Fire",
    "workbench.colorCustomizations": {
        "editorGutter.background": "#494949"
    }
}
```

<img width="1339" alt="Screen Shot 2020-07-19 at 10 22 00 pm" src="https://user-images.githubusercontent.com/31783266/87874575-44bfe100-ca0e-11ea-8e5a-2aec8c99fdb1.png">

Here’s the same gutter colour, but with a look that’s closer to the stripped-down UI I’m used to (and I guessing you too based on your config):

```json
{
    "workbench.colorTheme": "Pale Fire",
    "workbench.colorCustomizations": {
        "editorGutter.background": "#494949"
    },
    "editor.folding": false,
    "editor.lineNumbers": "off",
    "editor.glyphMargin": false,
    "editor.renderIndentGuides": false,
    "editor.minimap.enabled": false,
    "workbench.editor.showTabs": false
}
```

<img width="1339" alt="Screen Shot 2020-07-19 at 10 25 15 pm" src="https://user-images.githubusercontent.com/31783266/87874641-b8fa8480-ca0e-11ea-91f8-464c3a46204e.png">

I’d say that that’s a pretty good compromise; the only thing that needs to be changed IMHO is the line numbers – they have too low a contrast with the gutter colour for my taste.
