### ISSUE TITLE
Transfer the repo to @arzg?

### ISSUE THREAD

**Issue by matklad** [matklad/pale-fire#21]
Hey, @arzg, you've put significantly more work into maintaining this than I ever did. 

I think it makes sense to fully transfer the extension into your hands, if you wish so.

Repo transfer shouldn't be a problem, but I am less clear on extension transfer. Ie, it seems like it is impossible to switch to a new publisher id: https://github.com/microsoft/vscode/issues/21478#issuecomment-283118349

We can keep the status quo where CI publishes the stuff on my behalf, or we can publish a separate extension, and point this one to the new one.

**Comment by arzg** [comment]
By the looks of that comment you linked to, I think it’s better to keep the theme’s ownership as it is. Even if transferring the repo is easy, I think that the whole process becomes unworthwhile when you consider the difficulty (impossibility?) of transferring the extension, though. I’m glad you‘ve noticed my contributions, btw :)

**Comment by matklad** [comment]
Ok, closing then for now!
