### ISSUE TITLE
unsafe kw should be bold

### ISSUE THREAD

**Issue by matklad** [matklad/pale-fire#25]
![image](https://user-images.githubusercontent.com/1711539/103939642-24f7b300-513d-11eb-96a3-83a9288f71e1.png)

**Comment by arzg** [comment]
Hm, I’d say that was caused by 6be3cec, where font styles were cleared by default for all rules. I’ll introduce a new `FontStyle::Inherit` that can be used for cases like this where we explicitly want to inherit font styles from other rules that apply.
