### ISSUE TITLE
traced/untracted files seem to be inverted?

### ISSUE THREAD

**Issue by matklad** [matklad/pale-fire#27]
![image](https://user-images.githubusercontent.com/1711539/103999874-86a43580-51ae-11eb-9d64-bdad51e7cc46.png)

I would expect untracked files to be grey.

For the reference, emacs version

![image](https://user-images.githubusercontent.com/1711539/103999830-75f3bf80-51ae-11eb-95a8-96707a2d25cb.png)

**Comment by arzg** [comment]
That’s a concidence; my intention with dimming those subheaders was to distinguish them from diff text. I guess it makes sense that the filenames of untracked files wouldn’t be marked as subheaders by edamagit, but I agree that it does look quite strange with it being the way it is. Maybe orange could be used for the subheaders instead, to avoid making it look like they’ve been gitignored or are untracked?

**Comment by arzg** [comment]
Untracked files don’t get any sort of scope from edamagit, so we can’t change the colour of those from the default foreground.

<img width="389" alt="Screen Shot 2021-01-08 at 9 03 59 pm" src="https://user-images.githubusercontent.com/31783266/104002331-08b74d00-51f5-11eb-9ccc-d8255babb6e0.png">

**Comment by matklad** [comment]
I guess we can open an issue upstream?

**Comment by arzg** [comment]
I think we should only do that if we actually want to style untracked files. If we want the look of edamagit in VS Code to match the look of magit in Emacs, then we should make those subheadings bold and leave untracked files as they are.

**Comment by arzg** [comment]
I’ve matched the styling of edamagit subheaders to that of magit in f506a95.
