### ISSUE TITLE
Too much cyan

### ISSUE THREAD

**Issue by arzg** [matklad/pale-fire#28]
I often find that my screen looks like this:

<img width="713" alt="Screen Shot 2021-01-09 at 7 23 47 pm" src="https://user-images.githubusercontent.com/31783266/104086989-9015c680-52b0-11eb-80ca-fdc9bf54451b.png">

That’s too much cyan in my opinion. Here’s the original Zenburn for Vim:

![](https://kippura.org/images/zenburn.png)

And here’s a Zenburn port to Eclipse:

<img width="437" alt="Screen Shot 2021-01-09 at 7 30 10 pm" src="https://user-images.githubusercontent.com/31783266/104087053-1a5e2a80-52b1-11eb-85a8-b6e128ba4364.png"> (source: http://www.eclipsecolorthemes.org/?view=theme&id=2)

I’ve been trying to work some of these colours into Pale Fire, but haven’t been particularly successful.

**Comment by matklad** [comment]
the cyan and blues come from the Emacs version, while the vim one is more yellowish: 

![image](https://user-images.githubusercontent.com/1711539/104087460-ee22b980-5270-11eb-80e9-31c0d1b23234.png)


![image](https://user-images.githubusercontent.com/1711539/104087446-dcd9ad00-5270-11eb-9c04-485f9f48a961.png)

I do like cyan a lot and find emacs variation far more pleasing on the eye. However, we might be overdoing this indeed. I wonder if we should color method calls (not definitions) white, a-la IntelliJ Light theme?

![image](https://user-images.githubusercontent.com/1711539/104087643-676edc00-5272-11eb-9d65-d6b0662ed0f9.png)

For completness, here's IntelliJ darkula, which is a better rendition of vim's yellow on dark theme:

![image](https://user-images.githubusercontent.com/1711539/104087790-4d81c900-5273-11eb-9d19-2411405dc65c.png)

**Comment by bbqsrc** [comment]
One reason I like method calls to be distinguishable from the braces around the arguments in some manner is because it draws attention to what actual functionality is happening in a chain of calls, which is very common when manipulating any iterator in Rust and reasonably ends up with 4-5 methods in a chain in my experience. I can just go "ah yes, iter map filter collect is happening here" without having a focus a bit more, it's very useful.

I've never had too much trouble with the cyan usage in this theme, as it kind of acts as a "secondary white" in practice in how it's used anyway.

**Comment by arzg** [comment]
Maybe Pale Fire could inherit the yellowish types from the Vim theme? That might mean too little cyan, then. I guess numbers could also become cyan like in the Vim theme. Hmm, I’ll try something out later today.

**Comment by arzg** [comment]
Then again, a lot of the time it isn’t nearly as bad:

<img width="467" alt="Screen Shot 2021-01-10 at 10 45 26 am" src="https://user-images.githubusercontent.com/31783266/104110946-f4786a80-5330-11eb-9a23-7b29b2dc6a88.png">

I think this screenshot has a really nice balance of colours, actually. Maybe the ‘too much cyan’ thing is an unsolvable problem – you’re always going to come across code that uses a lot of e.g. functions, and then that code will be dominated by the colour that functions use.

**Comment by arzg** [comment]
My attempt at using the light yellow from the Vim theme:

<img width="707" alt="Screen Shot 2021-01-10 at 10 51 40 am" src="https://user-images.githubusercontent.com/31783266/104111029-d3644980-5331-11eb-9793-2f6d862ee202.png">

It definitely looks weird to me at the moment, but I’ll give it a try.

**Comment by arzg** [comment]
With only functions and method definitions highlighted:

<img width="713" alt="Screen Shot 2021-01-10 at 10 58 26 am" src="https://user-images.githubusercontent.com/31783266/104111121-c6942580-5332-11eb-92e0-7b95c639a601.png">

I agree with @bbqsrc, I think the highlighting was helpful

**Comment by arzg** [comment]
Only a few minutes into writing some code, and I’m already really frustrated with this change I’m trying out. I’m OK with closing this issue, because I guess you can’t have a theme that looks perfect with all kinds of code; that screenshot I posted at the start of this issue is an extreme example, and most code looks really good with the theme as it is.
