### ISSUE TITLE
Accessing unreleased changes

### ISSUE THREAD

**Issue by arzg** [matklad/pale-fire#3]
Hi,

I was just poking around the source of Pale Fire because I’m porting it for an editor I’m working on, and noticed that a bunch of the colours are different to those I’m used to seeing in VS Code. After looking some more, I realised that the last release was v0.1.0; around two months ago.

Is there some way I can try out the latest changes? Or would you have to release again for this? Is that something you would be comfortable with, or are these new colours not definitely going into the next release?

Thanks for Pale Fire by the way, it’s my favourite colour scheme for Rust at the moment (I tend to be very indecisive when it comes to colour schemes). rust-analyzer is amazing too, so good in fact you managed to get a lifelong (well, as long as I’ve been programming for) Vim user to switch to VS Code, without any kind of Vim emulation either!

**Comment by matklad** [comment]
Thanks for the poke, published! If you like Pale Fire, you might also enjoy https://github.com/drzix/hc-zenburn-vscode

**Comment by arzg** [comment]
Thank you, I took a look at hc-zenburn-vscode but I prefer Pale Fire :)
