### ISSUE TITLE
Differentiate highlighting of items that originate from traits

### ISSUE THREAD

**Issue by arzg** [matklad/pale-fire#34]
Now that rust-analyzer/rust-analyzer#8024 has been implemented, it would make sense to utilise rust-analyzer’s new highlighting capabilities to differentiate items that come from traits. I think this is a good idea because it can sometimes be confusing why a given type has a certain method or associated constant when this came from a trait. With highlighting, this becomes obvious at a glance.

**Comment by arzg** [comment]
@matklad what would you think of using italics for this instead of the `consuming` modifier?

**Comment by matklad** [comment]
Using italics here would work, yeah! Might also check what IntelliJ is doing in Kotlin for extension methods. 

But, if we use italics here, what should we do with consuming then?

**Comment by arzg** [comment]
Hmm, I’m not sure; I think bold would be too strong for both the `consuming` and `trait` modifiers, and underline is already being used for `mutable`. Maybe it would be better to use a colour for trait items instead?
