### ISSUE TITLE
Request: different colors for unresolved references and unsafe functions

### ISSUE THREAD

**Issue by thomcc** [matklad/pale-fire#38]
Right now they're the same color. This kinda makes sense, since they're both things you want to avoid, but in a very different way. I think they should be changed to different colors, but don't have very strong feelings about what.

I can override it locally (and probably will after filing this issue), but figured I'd say something.

**Comment by arzg** [comment]
Maybe we could make unresolved references underlined (as a reference to error squigglies) and lighten the red?

**Comment by thomcc** [comment]
That seems completely reasonable.

**Comment by thomcc** [comment]
That was fast, and it looks great!
