### ISSUE TITLE
Feedback on recent changes

### ISSUE THREAD

**Issue by arzg** [matklad/pale-fire#40]
@matklad @bbqsrc @thomcc

Hi all, sorry for the notification. I’ve made some significant changes to the highlighting of Pale Fire (0b90ada and f6cf62b), and would welcome feedback. I’m more than happy to revert the commits / do something entirely different, so please let me know what you think!

**Comment by thomcc** [comment]
I don't really like the bolding of public items.

I don't really care about the trait italicization (or, I'm weakly positive on it) or the unbolding of keywords (I guess weakly negative, but I'll probably get used to it).

That said, you don't need to revert any of this for my sake — if it continues to bug me, I can just override it on my own.

**Comment by arzg** [comment]
Thank you for your response.

Maybe I’m overthinking / assigning too much significance to highlighting, but I think it would be useful to highlight public items in some way, since extra care is needed when changing them – perhaps a colour would be better, instead of bold? Then again, it would be strange if, say, both public constant definitions and public method definitions had the same colour, since they use differing colours everywhere else.

I find using bold for keywords helps give the code more ‘structure’, for lack of a better term. On the other hand, keywords are hardly the most important element in code, so the emphasis might be better spent elsewhere.

**Comment by thomcc** [comment]
> perhaps a colour would be better, instead of bold?

I think a color difference would bother me less than bold, but I'm not sure what I think the right thing would be...

> I find using bold for keywords helps give the code more ‘structure’, for lack of a better term. On the other hand, keywords are hardly the most important element in code

I agree on the first point, and am unsure that I agree that they aren't the most important element in the code. Certainly other facts are important, but the keywords determine what it is the code does in a detailed way (e.g. an `if` controls whether or not a potentially large amount of code is executed). `trait` vs `impl` determines a great deal about what the contents of the body mean, etc.

**Comment by arzg** [comment]
Hmm, that is a good point. For now I think I’ll roll back the changes to boldness and leave public items unhighlighted.

Locally, I tried changing hue to differentiate public declarations (but keeping the existing lightness variations between e.g. structs and methods). Here’s an attempt using a hue similar to the purple that is included in [some versions of Zenburn](http://www.eclipsecolorthemes.org/?view=theme&id=2):

<img width="391" alt="Screen Shot 2021-07-01 at 11 25 59 pm" src="https://user-images.githubusercontent.com/31783266/124131993-b2e8a100-dac3-11eb-8f94-44e927e13c94.png">
<img width="617" alt="Screen Shot 2021-07-01 at 11 26 11 pm" src="https://user-images.githubusercontent.com/31783266/124132020-b9771880-dac3-11eb-868a-26941141f3a9.png">

Here the differences in lightness are much clearer:

<img width="145" alt="Screen Shot 2021-07-01 at 11 27 02 pm" src="https://user-images.githubusercontent.com/31783266/124132139-d7dd1400-dac3-11eb-8d2f-d8d5a5efad79.png">

<img width="144" alt="Screen Shot 2021-07-01 at 11 27 30 pm" src="https://user-images.githubusercontent.com/31783266/124132192-e9beb700-dac3-11eb-8c41-e1631f4bc8bb.png">

**Comment by thomcc** [comment]
> but I think it would be useful to highlight public items in some way, since extra care is needed when changing them

Hm, so, I'm sympathetic to this, but upon experimentation, it doesn't know if somethings *actually* public, and just marks it as this if the thing has a `pub` modifier, more or less — e.g. it will bold a `pub fn` on a unexported type, or a `pub struct` that is only used inside one crate.

That is, as it is, the bolding doesn't seem that valuable to me. That said, it's possible that this will improve in the future... Although, I think there's a very solid argument to be made that the current behavior is correct for `*.declaration.public`, since these *are* public declarations.

I guess what I'm saying is: I don't know that I find it valuable at the moment since many declarations that are public don't require care, it's only the ones that are public *and* exported. But again, perhaps there would be a way to support that in the future.

In the mean time, I'll probably turn off the bolding, since it's *just a bit* too eye-catching for my tastes. The alternative I was going to suggest was changing the background slightly, but honestly, that purple is quite nice looking aesthetically (IMO), and doesn't distract the way I find the bold to, so it's probably better (again, IMO).

And again, I'm fine with changing this stuff locally if I'm alone in these views.

**Comment by arzg** [comment]
> it doesn't know if somethings *actually* public, and just marks it as this if the thing has a `pub` modifier, more or less — e.g. it will bold a `pub fn` on a unexported type, or a `pub struct` that is only used inside one crate.

I guess that raises the question why those items are public, then 😁

By the way, items that are `pub` but aren’t accessible from outside the crate get a warning if you add `#![warn(unreachable_pub)]` to your crate root

> In the mean time, I'll probably turn off the bolding, since it's *just a bit* too eye-catching for my tastes. 

Just to let you know, I’ve just released v0.3.28 that reverts the change to bold.

> The alternative I was going to suggest was changing the background slightly

Unfortunately VS Code does not support this natively, and would require a full extension that injects custom CSS.

> but honestly, that purple is quite nice looking aesthetically (IMO), and doesn't distract the way I find the bold to, so it's probably better (again, IMO).
>
> And again, I'm fine with changing this stuff locally if I'm alone in these views.

I’m glad you like it; I think I’ll wait for others to weigh in before I make any other changes.

**Comment by ochado** [comment]
> > but honestly, that purple is quite nice looking aesthetically (IMO), and doesn't distract the way I find the bold to, so it's probably better (again, IMO).
> > And again, I'm fine with changing this stuff locally if I'm alone in these views.
> 
> I’m glad you like it; I think I’ll wait for others to weigh in before I make any other changes.

I also really like the way purple works for this, rather than bolding.

**Comment by arzg** [comment]
I’ve released the purple public declarations in 0.3.29; please let me know what your thoughts on the change are.

**Comment by ochado** [comment]
> I’ve released the purple public declarations in 0.3.29; please let me know what your thoughts on the change are.

Just tried it out now --- two thumbs up from me!

**Comment by matklad** [comment]
I am myself not sure how I feel about purple -- to me, it feels a bit that it creates unnecessary variety. There's a `pub` keyword to signify visibility, so burning a color for that feels a bit wasteful. On the other hand, I can't say that I positively dislike the purple, so I might get accustomed to it?

**Comment by matklad** [comment]
OTOH, for enums it does look excessive:

![image](https://user-images.githubusercontent.com/1711539/125190790-937e1080-e247-11eb-9e74-d4b77105c585.png)

**Comment by arzg** [comment]
@matklad

> I am myself not sure how I feel about purple -- to me, it feels a bit that it creates unnecessary variety. There's a `pub` keyword to signify visibility, so burning a color for that feels a bit wasteful.

Hmm, I see what you mean; `pub` is already there, so colour is only additional. Items from traits, on the other hand, are completely ‘invisible’ in their unqualified form, which I would say makes their highlighting more justified.

An example of another ‘invisible’ code property that is going unhighlighted at the moment is the distinction between enums, structs and type aliases. It is impossible to tell these apart in, say

```rust
// T is syntactically the same, regardless of whether
// T is a struct, enum or type alias
struct Wrapper(T);
```

Would you say these are sufficiently different to warrant the use of another colour for, say, enums, or is it better to remove the purple entirely?

Or perhaps type aliases, function parameters or lifetimes are better suited to using a new colour, since these all currently use colours that are already used elsewhere.

**Comment by matklad** [comment]
>An example of another ‘invisible’ code property that is going unhighlighted at the moment is the distinction between enums, structs and type aliases.

I think that's intentional -- all these (and unions also) are just types. That is, we *want* structs and enum to be mostly interchangeable. In contrast, traits are a different kind of thing, and they need separate color. 

> type parameters

I think this is an important distinction to highlight: in large scale, "is this generc?" has a pretty big implications, and I'd love for that to be visually distinct. 

> function parameters

Semantically, function parameters are the same as local variables. I personally don't see a benefit between distinguishing the two. 

>lifetimes

This are already lexically distinct (due to `'`), so I don't think we need to go out of the way supporting that. 

I don't have a value judgment as to what's the best use for the new color, I trust your taste more than mine :) 

That said, having run with this for ~month, I must say I find the new color aesthetically pleasing, sufficiently pale & burning! :purple_heart:

**Comment by matklad** [comment]
I think there's one more issues with pub = :purple_square:. The basic rule is "referencce color = definition color", but pub breaks that.

**Comment by arzg** [comment]
> I think that's intentional -- all these (and unions also) are just types. That is, we _want_ structs and enum to be mostly interchangeable. In contrast, traits are a different kind of thing, and they need separate color.

That does make sense, thanks for providing the rationale.

> I think this is an important distinction to highlight: in large scale, "is this generc?" has a pretty big implications, and I'd love for that to be visually distinct.

With this do you mean it’s important to highlight generic parameters, or that it would be good to highlight items that have generic parameters differently?

> Semantically, function parameters are the same as local variables. I personally don't see a benefit between distinguishing the two.

Good point; there are already a lot of things being highlighted in green, so I’ll remove function parameter highlighting.

> I don't have a value judgment as to what's the best use for the new color, I trust your taste more than mine :)

:)

> That said, having run with this for ~month, I must say I find the new color aesthetically pleasing, sufficiently pale & burning! 💜

I’m glad you like it!

> I think there's one more issues with pub = 🟪. The basic rule is "referencce color = definition color", but pub breaks that.

Potentially we could highlight both references and definitions of public items in purple, but IMO this would be going too far. Alternatively the purple could be used for items from traits, and italic be shifted back to the `consuming` modifier.

**Comment by thomcc** [comment]
I think highlighting the generic parameters (the params themselves) would be very valuable, and is probably a better use of the purple than the pub highlighting which I don't really find very useful (I don't dislike it enough to turn off, but since it's just "local" `pub`-ness, it's... kind of redundant with the `pub` keyword).

I am in favor of keeping the function arg highlighting though. I like being able to distinguish at a glance the values that are directly user-controlled. That said, I admit that this argument is kind of flimsy, and I don't mind turning it on myself if I'm alone here.

**Comment by arzg** [comment]
> I think highlighting the generic parameters (the params themselves) would be very valuable, and is probably a better use of the purple than the pub highlighting which I don't really find very useful (I don't dislike it enough to turn off, but since it's just "local" `pub`-ness, it's... kind of redundant with the `pub` keyword).

Generic parameters are already highlighted in orange; would you say it’s preferable to use purple for generic parameters to differentiate them from struct fields and lifetimes (the other things that use orange)?

> I am in favor of keeping the function arg highlighting though. I like being able to distinguish at a glance the values that are directly user-controlled. That said, I admit that this argument is kind of flimsy, and I don't mind turning it on myself if I'm alone here.

Do you think that using a colour slightly lighter or darker than the standard variable colour would be better than the green used previously? I found the green became a bit much previously (numbers, namespaces, comments, parameters), and a subtle brightness change would be less obtrusive.

> -1 here, I don't care if a function I'm calling is public, since it doesn't impact really anything at all (obviously it's public enough for me to call, which is all that really matters...).
> 
> (It would also lead to an explosion of purple)

Yep, I agree with this.

**Comment by thomcc** [comment]
> Generic parameters are already highlighted in orange

Ah, right, I meant on the usage site, but they should stay orange for that consistency, as mentioned earlier in the thread.

> Do you think that using a colour slightly lighter or darker than the standard variable colour would be better than the green used previously? I found the green became a bit much previously (numbers, namespaces, comments, parameters), and a subtle brightness change would be less obtrusive.

That makes sense, and yeah, slightly lighter/darker seems reasonable.

**Comment by arzg** [comment]
@thomcc I released a version that dims parameters slightly. I’m undecided about it, so I’d be especially interested to know whether you think it’s better to leave parameters unhighlighted, or to use the old green colour.

**Comment by arzg** [comment]
Would you prefer I remove the parameter highlighting, in that case? I find it looks a little strange, but don’t find it particularly helpful or harmful.

**Comment by arzg** [comment]
I’ve adjusted the highlighting of attributes so contained syntax gets its own appropriate highlighting. Although I guess this is more technically ‘correct’ (and makes it more obvious that go to definition on the functions in the salsa example works), I think it might be more visually noisy?

<table>
  <tr><th>0.4.15</th><th>0.4.16</th></tr>
  <tr>
    <td><img alt="Screen Shot 2021-12-24 at 9 00 29 am" src="https://user-images.githubusercontent.com/31783266/147294865-815cfba8-ecd2-4282-ae9b-b6ae65e90689.png"></td>
    <td><img alt="Screen Shot 2021-12-24 at 9 00 08 am" src="https://user-images.githubusercontent.com/31783266/147294884-236267ac-3894-42d4-9264-90be1efb0cab.png"></td>
  </tr>
  <tr>
    <td><img alt="Screen Shot 2021-12-24 at 9 01 01 am" src="https://user-images.githubusercontent.com/31783266/147294940-3216b40b-e188-4e94-8dc8-c0b255414c44.png"></td>
    <td><img alt="Screen Shot 2021-12-24 at 9 01 08 am" src="https://user-images.githubusercontent.com/31783266/147294961-00857024-0f61-4d70-836f-1c62fa341ea5.png"></td>
  </tr>
</table>

**Comment by arzg** [comment]
Another option is to highlight derive macros as traits, since they often (?) expand to a trait implementation.

<img width="401" alt="Screen Shot 2021-12-24 at 9 10 48 am" src="https://user-images.githubusercontent.com/31783266/147295385-262ebff5-5a34-4c17-8492-f418418cc611.png">
