### ISSUE TITLE
Macro definitions could benefit from more syntax highlighting

### ISSUE THREAD

**Issue by Cldfire** [matklad/pale-fire#41]
I've been writing more macros lately, and one thing I've noticed is that pale-fire's highlighting of macro definitions makes things a bit difficult to read.

For instance, here's a macro definition syntax-highlighted by Gitlab's diff viewer:

![Screen Shot 2021-07-19 at 10 11 27 AM](https://user-images.githubusercontent.com/13814214/126173760-7fad1da2-d625-48cf-bc5d-3a4077018715.png)

Here's that same macro definition in pale-fire:

![Screen Shot 2021-07-19 at 10 11 48 AM](https://user-images.githubusercontent.com/13814214/126173821-ca48102d-3008-4acd-a22f-cb7f742abb1f.png)

Gitlab's syntax highlighting provides helpful color differentiation for important bits of the macro definition here, such as the `$` symbol and the argument definitions / designators. Pale-fire lacks color and everything turns into one blob, making it harder to read.

**Comment by arzg** [comment]
Do you think it would be helpful to highlight macro parameters the same way normal function parameters are currently highlighted, namely in green?

**Comment by arzg** [comment]
And maybe [fragment specifiers](https://veykril.github.io/tlborm/macros/minutiae/fragment-specifiers.html) could be highlighted as primitive types?

**Comment by Cldfire** [comment]
Yeah, that sounds like it could work well to me :)

**Comment by arzg** [comment]
I’ve made the changes in 36f75eb; would you say this issue can now be closed?

**Comment by Cldfire** [comment]
Thank you! I've used it for a few days and it's worked well in my experience. Closing :)
