### ISSUE TITLE
Vim Version

### ISSUE THREAD

**Issue by errantmind** [matklad/pale-fire#48]
I like Vim (neovide / neovim) more than I like VSCode and would prefer to use that, but it is hard to not have this delightful semantic highlighting and color scheme when working on my Rust programs.

Is there a Vim version of this, preferably with semantic highlighting? I'm using Coc w/ rust-analyzer

**Comment by matklad** [comment]
I believe this actually originated in Vim-land: https://kippura.org/zenburnpage/

**Comment by errantmind** [comment]
Looks nice, but this repo is better, especially with the semantic highlighting.

**Comment by errantmind** [comment]
Thanks (all contributors) for making this theme , it is my favorite. I will close this now.
